"""Add ontrol input field

Revision ID: 9641285ca9d7
Revises: d39156cb45f2
Create Date: 2021-08-20 18:16:43.414736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9641285ca9d7'
down_revision = 'd39156cb45f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('input', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control', 'input')
    # ### end Alembic commands ###
