"""add grow system/property models

Revision ID: 53f36208ed3e
Revises: 80c2ca7de8c5
Create Date: 2021-09-07 13:51:22.017184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f36208ed3e'
down_revision = '80c2ca7de8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grow_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grow_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grow_system_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grow_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grow_system_id'], ['grow_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grow_property_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('grow_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.ForeignKeyConstraint(['grow_system_id'], ['grow_system_instance.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['grow_property.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grow_property_instance')
    op.drop_table('grow_system_instance')
    op.drop_table('grow_system')
    op.drop_table('grow_property')
    # ### end Alembic commands ###
